name: table
description: A table like data structure for Dart
version: 2.2.0
homepage: https://github.com/thumbert/table.git
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  csv: ^6.0.0
  dama:
    git: https://github.com/thumbert/dama.git
  more: ^4.0.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.16.5


