name: table
description: A table like data structure for Dart
version: 1.0.0
author: Tony Humbert <tony.humberts@gmail.com>
homepage: https://github.com/thumbert/table.git

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  csv: ^4.0.0
  dama:
    git:
      url: git://github.com/thumbert/dama.git
  more: ^1.10.1

dev_dependencies:
  pedantic: ^1.9.0
  test: '>=1.0.0 <2.0.0'
