name: table
description: A table like data structure for Dart
version: 0.0.1
author: Tony Humbert <humbert.tony@yahoo.com>
homepage: https://github.com/thumbert/table.git

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  more: '^1.4.0'

dev_dependencies:
  csv: '^2.0.1'
  test: '>=0.12.0 <0.13.0'
