name: table
description: A table like data structure for Dart
version: 2.0.0
author: Tony Humbert <tony.humberts@gmail.com>
homepage: https://github.com/thumbert/table.git

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  csv: ^5.0.0-nullsafety.0
  dama:
    git:
      url: git://github.com/thumbert/dama.git
  more: ^3.0.1
  test: ^1.16.5

dev_dependencies:
  pedantic: ^1.11.0

